development:
  sessions:
    default:
      database: bundle-240 #pophealth-development
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: pophealth-test
      hosts:
        - localhost:27017
production:
  sessions:
    default:
      database: pophealth-production
      hosts:
        - localhost:27017
