defaults: &defaults
  # idle timeout settings
  idle_timeout_enabled: true
  idle_timeout: 300000
  # user should have the staff role by default when created (this allows users to see data accross all providers)
  default_user_staff_role: false
  # user should be approved by default when created
  default_user_approved: true
  # display logout link
  logout_enabled: true
  # should the account link be displayed in the header
  edit_account_enabled: true
  # should new accounts be creatable, and should a user be able to edit their account
  allow_user_update: true
  # add patient management link
  patient_management_enabled: true
  # title of the practice
  practice_name: 'General Hospital'
  disable_provider_filters: false
  ccr_system_name: popHealth
  # force the system to allow HTTP connections
  force_unsecure_communications: true
  use_map_reduce_prefilter: true
  enable_map_reduce_rationale: true
  enable_map_reduce_logging: true
  #use provider opml heirarchy instead of practice based system
  use_opml_structure: false
  #provider type to exclude EH measures from
  eh_exclusion_type: "Division"
  orphan_provider:
    root: "popHealth"
    extension: "Orphans"
  value_sets:
    ticket_url: https://vsac.nlm.nih.gov/vsac/ws/Ticket
    api_url: https://vsac.nlm.nih.gov/vsac/ws/RetrieveValueSet
  cda_header:
    :identifier:
      :root:
      :extension:
    :authors:
    - :ids:
      - :root: author_root
        :extension: author_extension
      :device:
        :name: device_name
        :model: device_model
      :addresses: []
      :telecoms: []
      :time:
      :organization:
        :ids:
        - :root: authors_organization_root
          :extension: authors_organization_ext
        :name: ''
    :custodian:
      :ids:
      - :root: custodian_root
        :extension: custodian_ext
      :person:
        :given: ''
        :family: ''
      :organization:
        :ids:
        - :root: custodian_rganization_root
          :extension: custodian_organization_ext
        :name: ''
    :legal_authenticator:
      :ids:
      - :root: legal_authenticator_root
        :extension: legal_authenticator_ext
      :addresses: []
      :telecoms: []
      :time:
      :person:
        :given:
        :family:
      :organization:
        :ids:
        - :root: legal_authenticator_org_root
          :extension: legal_authenticator_org_ext
        :name: ''

development:
  <<: *defaults
  idle_timeout_enabled: false
  default_user_staff_role: true
  patient_management_enabled: true

test:
  <<: *defaults
  default_user_approved: false
  # we do not want to force unsecure when testing
  force_unsecure_communications: true

production:
  <<: *defaults
  default_user_staff_role: false
  default_user_approved: false
